apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: task-service
          image: ghcr.io/proops2026-taskmanager/task-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: task-svc-secret
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: task-svc-secret
                  key: REDIS_URL
            - name: PORT
              value: "3002"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 10
